springdoc:
  swagger-ui:
    operations-sorter: method
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  security:
    user:
      password: 1
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

